// <auto-generated />
using System;
using LineBotAccountRecorder.Dal.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LineBotAccountRecorder.Dal.Migrations
{
    [DbContext(typeof(AccountRecorderDbContext))]
    [Migration("20210707173633_AddAccountRecourd")]
    partial class AddAccountRecourd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LineBotAccountRecorder.Dal.Models.AccountRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AccountRecordStatus")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("Amount")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Debtor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
